const express = require('express')
const app = express()
const adminRouter = require('./adminRouter')
const pedidoRouter  = require('./pedidosRouter')
const stockRouter = require('./feedbackRouter')
const messageRouter = require('./messageRouter')
const usuario = require('./UsuarioRouter')
app.use(adminRouter)
app.use(pedidoRouter)
app.use(stockRouter)
app.use(messageRouter)
app.use(usuario)
module.exports = app